matrix:
  include:
    - os: linux
      language: go
      python: 2.7
      sudo: required
      services:
        - mysql
      env:
        - MYSQL_TEST_USER=travis
        - MYSQL_TEST_ADDR=127.0.0.1:3306
      before_install:
        - for f in $(find . -type f); do sed -i 's:github.com\/google\/fleetspeak:github.com/demonchild2112/fleetspeak-test:g' $f; done
        - sudo pip install --upgrade pip virtualenv
        - virtualenv "${HOME}/FSENV"
        - mysql --print-defaults
        #- go get -u github.com/golang/lint/golint
      install:
        - source "${HOME}/FSENV/bin/activate" && pip install -e .
        - go get -v -t ./... # Install dependencies needed for tests.
      script:
        # We want to address all golint warnings, except for
        # https://github.com/golang/go/wiki/CodeReviewComments#doc-comments
        # - golint ./... | grep -v 'should have comment or be unexported'
        - go vet ./... || true
        - source "${HOME}/FSENV/bin/activate"
        - fleetspeak/build.sh && fleetspeak/test.sh

    # Note that mysql is not available in OSX environments.
    - os: osx
      language: go
      python: 2.7
      before_install:
        - for f in $(find . -type f); do sed -i~ 's:github.com\/google\/fleetspeak:github.com/demonchild2112/fleetspeak-test:g' $f; done
        - git clone https://github.com/MacPython/terryfy
        # Install pip.
        - >-
          source terryfy/travis_tools.sh &&
          get_python_environment macpython 2.7.14
        - pip install --upgrade pip virtualenv
        - virtualenv "${HOME}/FSENV"
        - go version
      install:
        - source "${HOME}/FSENV/bin/activate" && pip install -e .
        - go get -v -t ./... # Install dependencies needed for tests.
      script:
        - source "${HOME}/FSENV/bin/activate"
        - fleetspeak/build.sh && fleetspeak/test.sh
