language: go

python: 2.7

# go_import_path: ${GOPATH}/src/github.com/google/fleetspeak

before_install:
  - for f in $(find . -type f); do sed -i 's:github.com\/google\/fleetspeak\/fleetspeak:github.com/demonchild2112/fleetspeak-test/fleetspeak-test:g' $f; done
  #- pip install --upgrade pip virtualenv
  #- virtualenv "${HOME}/FSENV"

install:
  #- source "${HOME}/FSENV/bin/activate" && pip install -e .
  - go get -v -t ./... # Install dependencies needed for tests.

script:
  # - source "${HOME}/FSENV/bin/activate"
  - fleetspeak-test/build.sh # && fleetspeak/test.sh
