platform: x64

image:
- Visual Studio 2017

# Clone repo to where the go toolchain expects it to be.
clone_folder: C:\gopath\src\github.com\google\fleetspeak

# Set GOPATH so the go toolchain can find the repo.
#
# Default GOROOT is C:\go, which is where appveyor installs the latest
# version of go (so no need to define the env variable here).
environment:
  GOPATH: C:\gopath
  PATH: '%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin'

install:
- python --version
- go version
- ps: Write-Output $env:PATH
- go get -v -t ./...  # Install dependencies.

build_script:
- >-
  go build -o fleetspeak/src/client/socketservice/testclient/testclient.exe
  github.com/google/fleetspeak/fleetspeak/src/client/socketservice/testclient
- >-
  go build -o fleetspeak/src/client/daemonservice/testclient/testclient.exe
  github.com/google/fleetspeak/fleetspeak/src/client/daemonservice/testclient

test_script:
- go test ./... --timeout 90s

